StoreApp/WebUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerBL _customerBL;
        private ILocationBL _locationBL;
        public CustomerController(ICustomerBL customerBL, ILocationBL locationBL)
        {
            _customerBL = customerBL;
            _locationBL = locationBL;
        }
        public ActionResult Index()
        {
            // You have different kinds of Views:
            // Strongly typed views - tied to a model, you declare the model at the top of the page with
            //                          @model DataType
            // Weakly typed views - not tied to a model. You can still pass data to it via, viewbag
            //                      viewdata, tempdata etc
            // Dynamic views - pass a model, let view figure it out. @model dynamic
            // This is an example of a strongly typed view
            return View(_customerBL
                .GetAllCustomers()
                .Select(customer => new CustomerVM(customer))
                .ToList()
                );
        }

        public ActionResult Main(int customerId)
        {
            //ViewBag.Location = _locationBL.GetLocationById(1);
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(CustomerVM customerVM)
        {
            Customer customer = _customerBL.GetCustomerByPhone(customerVM.PhoneNumber);
            return RedirectToAction(nameof(Main), new {customerId = customer.Id});
        }

        // GET: CustomerController/Create
        public ActionResult Create(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerVM customerVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string message = "";
                    Customer exist = _customerBL.GetCustomerByPhone(customerVM.PhoneNumber);
                    if (exist != null)
                    {
                        message ="Please try again. An account already exists";
                        return RedirectToAction(nameof(Create), new {message = message});
                    }
                    Customer current = new Customer
                    {
                        FirstName = customerVM.FirstName,
                        MiddleName = customerVM.MiddleName,
                        LastName = customerVM.LastName,
                        PhoneNumber = customerVM.PhoneNumber
                    };
                    _customerBL.AddCustomer(current);
                    Customer customer = _customerBL.GetCustomer(current);
                    return RedirectToAction(nameof(Main), new {customerId = customer.Id});
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreApp/WebUI/Controllers/LocationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;

namespace WebUI.Controllers
{
    
    public class LocationController : Controller
    {
        private ILocationBL _locationBL;
        private ICustomerBL _customerBL;
        public LocationController(ILocationBL locationBL, ICustomerBL customerBL)
        {
            _locationBL = locationBL;
            _customerBL = customerBL;
        }

        public ActionResult Index()
        {
            return View(_locationBL
            .GetAllLocations()
            .Select(location => new LocationVM(location))
            .ToList()
            );
        }
        
        public ActionResult SelectLocation(int customerId)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            return View(_locationBL
            .GetAllLocations()
            .Select(location => new LocationVM(location))
            .ToList()
            );
        }
        
        public ActionResult Main(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            return View();
        }

        //GET
        public ActionResult Create()
        {
            return View();
        }
        
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LocationVM locationVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _locationBL.AddLocation(new Location
                    {
                        Name = locationVM.Name,
                        Address = locationVM.Address
                    });
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreApp/WebUI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebUI.Controllers
{
    public class OrderController : Controller
    {
        private IProductBL _productBL;
        private ILocationBL _locationBL;
        private ICustomerBL _customerBL;
        private IInventoryBL _inventoryBL;
        private IOrderBL _orderBL;

        public OrderController(IProductBL productBL, ILocationBL locationBL, ICustomerBL customerBL, IInventoryBL inventoryBL, IOrderBL orderBL)
        {
            _productBL = productBL;
            _locationBL = locationBL;
            _customerBL = customerBL;
            _inventoryBL = inventoryBL;
            _orderBL = orderBL;
        }

        public ActionResult SelectProduct(int locationId, int customerId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            return View(_inventoryBL
                .GetUnselectedProducts(_locationBL.GetLocationById(locationId), customerId)
                .Select(
                    inventory => new InventoryVM()
                    {
                        Id = inventory.Id,
                        Quantity = inventory.Quantity,
                        Product = _productBL.GetProductById(inventory.ProductId)
                    })
                .ToList()
            );
        }

        public ActionResult Sort(int customerId)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            return View();
        }

        public ActionResult History(int customerId, string sortingCode)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            return View(_orderBL
                .GetAllOrderByCustomer(customerId, sortingCode)
                .Select(
                    order => new OrderVM()
                    {
                        Id = order.Id,
                        OrderDate = order.OrderDate,
                        Total = order.Total,
                        Location = _locationBL.GetLocationById(order.LocationId)
                    }
                )
                .ToList()
            );
        }

        public ActionResult Detail(int customerId, int orderId, int locationId, decimal total)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            ViewBag.Total = total;
            return View(_orderBL
                .GetOrderItemByOrderId(orderId)
                .Select(
                    item => new ItemVM()
                    {
                        Id = item.Id,
                        Quantity = item.Quantity,
                        Product = _productBL.GetProductById(item.ProductId),
                        Amount = item.Quantity * _productBL.GetProductById(item.ProductId).Price
                    }
                )
                .ToList()
            );
        }

        public ActionResult AddToCart(int customerId, int locationId, int inventoryId, int productId, int id, string message)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            ViewBag.Inventory = _inventoryBL.GetInventoryById(inventoryId);
            ViewBag.Product = _productBL.GetProductById(productId);
            ViewBag.Message = message;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToCart(CartVM cart)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string message = "";
                    Inventory stock = _inventoryBL.GetInventoryById(cart.InventoryId);
                    if (cart.Quantity > stock.Quantity)
                    {
                        message = $"Try again. We don't have {cart.Quantity} {cart.Name} in stock!";
                        return RedirectToAction(nameof(AddToCart), new {locationId = cart.LocationId, 
                                                                        customerId = cart.CustomerId,
                                                                        inventoryId = cart.InventoryId,
                                                                        productId = cart.ProductId,
                                                                        id = cart.Id,
                                                                        message = message
                                                                        });

                    }
                    _orderBL.AddToCart(
                        new Cart
                        {
                            LocationId = cart.LocationId,
                            CustomerId = cart.CustomerId,
                            InventoryId = cart.InventoryId,
                            ProductId = cart.ProductId,
                            Quantity = cart.Quantity,
                            Price = cart.Price,
                            Name = cart.Name
                        }
                    );
                    return RedirectToAction(nameof(SelectProduct), new {locationId = cart.LocationId, customerId = cart.CustomerId});
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Checkout(int locationId, int customerId, string message)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            ViewBag.Message = message;

            Tuple<List<Cart>, decimal> result = _orderBL.GetAllCartItems(customerId);
            if (result.Item1.Count > 0 )
            {
                ViewData.Add("Total", result.Item2);
            }
            else
            {
                ViewData.Add("Total", "No item in the cart yet");
            }
            return View(result.Item1
                .Select(
                    cart => new CartVM
                        {
                            Id = cart.Id,
                            LocationId = cart.LocationId,
                            CustomerId = cart.CustomerId,
                            InventoryId = cart.InventoryId,
                            ProductId = cart.ProductId,
                            Quantity = cart.Quantity,
                            Price = cart.Price,
                            Name = cart.Name,
                            Total = cart.Quantity * cart.Price,
                            Location = cart.Location
                        })
                .ToList()
            );
        }

        public ActionResult Main(int customerId, int locationId)
        {
            string message = "Can't place order. Your cart is empty";
            try
            {
                ViewBag.Customer = _customerBL.GetCustomerById(customerId);
                ViewBag.Location = _locationBL.GetLocationById(locationId);
                Tuple<List<Cart>, decimal> result = _orderBL.GetAllCartItems(customerId);
                if (result.Item1.Count > 0 )
                {
                    int proceed = _orderBL.ProcessOrder(customerId);
                    ViewData.Add("Message", "Your order has been placed!");
                    return View();
                }
                //ViewData.Add("Message", "Your cart is empty");
                
                return RedirectToAction(nameof(Checkout), new {locationId = locationId, customerId = customerId, message = message});
            }
            catch
            {
                return RedirectToAction(nameof(Checkout), new {locationId = locationId, customerId = customerId, message = message});
            }

        }

        public ActionResult Edit(int id)
        {
            CartVM item = new CartVM(_orderBL.GetCartItem(id));
            ViewBag.Customer = _customerBL.GetCustomerById(item.CustomerId);
            ViewBag.Location = _locationBL.GetLocationById(item.LocationId);
            ViewBag.Inventory = _inventoryBL.GetInventoryById(item.InventoryId);
            ViewBag.Product = _productBL.GetProductById(item.ProductId);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CartVM cart)
        {
            string message = "";
            try{
                if (ModelState.IsValid)
                {
                    _orderBL.UpdateCartItem(                        
                        new Cart
                        {
                            Id = cart.Id,
                            LocationId = cart.LocationId,
                            CustomerId = cart.CustomerId,
                            InventoryId = cart.InventoryId,
                            ProductId = cart.ProductId,
                            Quantity = cart.Quantity,
                            Price = cart.Price,
                            Name = cart.Name
                        }
                    );
                    message = cart.Name + " is updated";
                    return RedirectToAction(nameof(Checkout), new {locationId = cart.LocationId, customerId = cart.CustomerId, message = message});
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Create(int customerId, int locationId)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);

StoreApp/WebUI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;
using System.Collections.Generic;

namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductBL _productBL;
        private ILocationBL _locationBL;
        public ProductController(IProductBL productBL, ILocationBL locationBL)
        {
            _productBL = productBL;
            _locationBL = locationBL;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UnclaimedList(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);

            return View(_productBL
            .GetUnclaimedProducts(_locationBL.GetLocationById(locationId))
            .Select(prod => new ProductVM(prod))
            .ToList()
            );
        }

        //GET
        public ActionResult Create(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductVM productVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _productBL.AddProduct(new Product
                    {
                        Name = productVM.Name,
                        Price = productVM.Price,
                        Description = productVM.Description
                    }
                    );
                    return RedirectToAction(nameof(UnclaimedList), new { locationId = productVM.LocationId });
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

    }
}

StoreApp/WebUI/Views/Order/AddToCart.cshtml
@model WebUI.Models.CartVM

@{
    ViewData["Title"] = "AddToCart";
}

<h2>Hello @ViewBag.Customer.FirstName</h2>
<hr />
<br>
<h3>Product Details</h3>
<h4>Store: @ViewBag.Location.Name</h4>
<h4>Name: @ViewBag.Product.Name</h4>
<h4>Price: @ViewBag.Product.Price</h4>
<h4>stock left @ViewBag.Inventory.Quantity</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddToCart">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
                <br>
                <p>
                    @ViewBag.Message
                </p>
            </div>
            <input type="hidden" asp-for="LocationId" value=@ViewBag.Location.Id/>
            <input type="hidden" asp-for="CustomerId" value=@ViewBag.Customer.Id/>
            <input type="hidden" asp-for="InventoryId" value=@ViewBag.Inventory.Id/>
            <input type="hidden" asp-for="ProductId" value=@ViewBag.Product.Id/>
            <input type="hidden" asp-for="Name" value=@ViewBag.Product.Name/>
            <input type="hidden" asp-for="Price" value=@ViewBag.Product.Price/>
            
            <div class="form-group">
                <input type="submit" value="Add to Cart" class="btn btn-primary" />

            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Cancel", "SelectProduct", "Order", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StoreApp/WebUI/Views/Order/Checkout.cshtml
@model IEnumerable<WebUI.Models.CartVM>
@{
    ViewData["Title"] = "Checkout";
    var customer = @ViewBag.Customer;
}

<h2>Hello @customer.FirstName</h2>
<hr />
<br>
<h3>Cart Details</h3>
<h5>Total : @ViewData["Total"]</h5>

<div class="text-right">
    <p>
        @Html.ActionLink("Continue Shopping", "SelectProduct", "Order", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id})
    </p>
    <br>
    <p>
        @ViewBag.Message
    </p>
</div>

<div>
    <table class="table">
        <thead>
            <tr>
                @* Show location here *@
                <th>
                    @* @Html.DisplayNameFor(model => model.Location.Name) *@
                    Location
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Order", new { id = item.Id }) |
                    @Html.ActionLink("Remove", "Delete", "Order", new { id = item.Id })
                </td>
            </tr>
    }
        </tbody>
    </table>
</div>

<br>
<div>
    @Html.ActionLink("Place the order", "Main", "Order", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id})
</div>

<br>
<div>
    @Html.ActionLink("Back to Main", "Main", "Customer", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id})
</div>

StoreApp/WebUI/Views/Order/Detail.cshtml
@model IEnumerable<WebUI.Models.ItemVM>
@{
    ViewData["Title"] = "Detail";
    var customer = @ViewBag.Customer;
}

<h2>Hello @customer.FirstName</h2>
<h4>Your Store: @ViewBag.Location.Name</h4>
<hr />
<br>
<h3>Order Details</h3>
<h5>Total : @ViewBag.Total</h5>

<div class="text-right">
    <p>
        @Html.ActionLink("Back to History", "History", "Order", new { customerId = ViewBag.Customer.Id})
    </p>
    <br>
</div>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Amount)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
            </tr>
    }
        </tbody>
    </table>
</div>

<br>
<div>
    @Html.ActionLink("Back to Main", "Main", "Customer", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id})
</div>

StoreApp/WebUI/Views/Order/History.cshtml
@model IEnumerable<WebUI.Models.OrderVM>
@{
    ViewData["Title"] = "History";
}

<h2>Hello @ViewBag.Customer.FirstName</h2>
@* <h4>Your Store: @ViewBag.Location.Name</h4> *@
<hr />
<br>
<h3>Order Histories</h3>

<div class="text-right">
    <p>
        @Html.ActionLink("Go back to option", "Sort", "Order", new { customerId = ViewBag.Customer.Id})
    </p> 
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.Name)
            </td>
            <td>
                @Html.ActionLink("View Details", "Detail", "Order", new { 
                                                                    customerId = ViewBag.Customer.Id, 
                                                                    orderId = item.Id,
                                                                    locationId = item.Location.Id,
                                                                    Total = item.Total
                                                                    })
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    @Html.ActionLink("Back to Main", "Main", "Customer", new { customerId = ViewBag.Customer.Id})
</div>

StoreApp/WebUI/Views/Order/Main.cshtml
@model IEnumerable<WebUI.Models.CartVM>
@{
    ViewData["Title"] = "Main";
}
<div class="text-center">
    <h3> Hey @ViewBag.Customer.FirstName, @ViewData["Message"]</h3> 

    <br>
    <div>
        @Html.ActionLink("Back to Main", "Main", "Customer", new { customerId = ViewBag.Customer.Id})
    </div>
    
    <br>
    <div>
        @Html.ActionLink("Continue Shopping", "SelectProduct", "Order", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id})
    </div>
</div>

StoreApp/WebUI/Views/Order/SelectProduct.cshtml
@model IEnumerable<WebUI.Models.InventoryVM>
@{
    ViewData["Title"] = "SelectProduct";
}

<h2>Hello @ViewBag.Customer.FirstName</h2>
<hr />
<br>
<h3>Select BBT you want to order in Store: @ViewBag.Location.Name</h3>

<div class="text-right">
    <p>
        @Html.ActionLink("View Cart", "Checkout", "Order", new { locationId = ViewBag.Location.Id, customerId = ViewBag.Customer.Id, message = ""})
    </p>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Price)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Price)
            </td>
            @* <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td> *@
            <td>
                @Html.ActionLink("Select", "AddToCart", "Order", new {customerId = ViewBag.Customer.Id, 
                                                                    locationId = ViewBag.Location.Id, 
                                                                    inventoryId = item.Id,
                                                                    productId = item.Product.Id,
                                                                    message = ""
                                                                    })
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    @Html.ActionLink("Back to Main", "Main", "Customer", new { customerId = ViewBag.Customer.Id})
</div>

StoreApp/WebUI/Views/Order/Sort.cshtml
@model IEnumerable<WebUI.Models.CartVM>
@{
    ViewData["Title"] = "Sort";
}
<div class="text-center">
    @* <h4>Hey @ViewBag.Customer.FirstName, please choose the sorting option:</h4>  *@

    <h6>Sort by Date</h6>
    <hr/>

    <br>
    <div>
        @Html.ActionLink("Ascending", "History", "Order", new { customerId = ViewBag.Customer.Id, sortingCode = "2"})
    </div>

    <br>
    <div>
        @Html.ActionLink("Descending", "History", "Order", new { customerId = ViewBag.Customer.Id, sortingCode = "3"})
    </div>
    <br>
    
    <br>
    <h6>Sort by Cost</h6>
    <hr/>

    <br>
    <div>
        @Html.ActionLink("Ascending", "History", "Order", new { customerId = ViewBag.Customer.Id, sortingCode = "0"})    
    </div>

    <br>
    <div>
        @Html.ActionLink("Descending", "History", "Order", new { customerId = ViewBag.Customer.Id, sortingCode = "1"})
    </div>
    <br>

    <br>
    <div>
        @Html.ActionLink("Back to Main", "Main", "Customer", new { customerId = ViewBag.Customer.Id})
    </div>

</div>

StoreApp/WebUI/Views/Order/Start.cshtml
@model IEnumerable<WebUI.Models.OrderVM>
@{
    ViewData["Title"] = "Start";
    var stock = ViewBag.Stock;
}

<h2>Hello @ViewBag.Customer.FirstName</h2>
<h4>Your Store: @ViewBag.Location.Name</h4>
<hr />
<br>
<h3>Available Products:</h3>

@* <p>
    &#128269;Can't find the Inventory. &#128073;
    @Html.ActionLink("Add New One", "AvailableList", "Product", new { locationId = ViewBag.Location.Id})
</p> *@

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in stock) {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Product.Name
            </td>
            <td>
                @item.Product.Price
            </td>
            <td>
                @item.Quantity
            </td>
            <td>
                @Html.ActionLink("View", "Create", "Order", new { customerId = ViewBag.Customer.Id, locationId = ViewBag.Location.Id })
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    @Html.ActionLink("Back to Main", "Option", "Location", new { locationId = ViewBag.Location.Id})
</div>