StoreApp/WebUI/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class InventoryController : Controller
    {
        private IInventoryBL _inventoryBL;
        private ILocationBL _locationBL;
        private IProductBL _productBL;
        public InventoryController(ILocationBL locationBL, IProductBL productBL, IInventoryBL inventoryBL)
        {
            _locationBL = locationBL;
            _productBL = productBL;
            _inventoryBL = inventoryBL;
        }

        public ActionResult Index()
        {
            return View();
        }   
        
        public ActionResult ReplenishList(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);

            return View(_inventoryBL
                .GetInventories(_locationBL.GetLocationById(locationId))
                .Select(
                    inventory => new InventoryVM()
                    {
                        Id = inventory.Id,
                        Quantity = inventory.Quantity,
                        Product = _productBL.GetProductById(inventory.ProductId)
                    })
                .ToList()
            );
        }

        public ActionResult Create(int locationId, int productId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            ViewBag.Product = _productBL.GetProductById(productId);
            return View(new InventoryVM(locationId, productId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InventoryVM inventoryVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _inventoryBL.AddInventory(
                        _locationBL.GetLocationById(inventoryVM.LocationId),
                        _productBL.GetProductById(inventoryVM.ProductId),
                        new Inventory
                        {
                            Quantity = inventoryVM.Quantity
                        }
                    );
                    return RedirectToAction(nameof(ReplenishList), new { locationId = inventoryVM.LocationId} );
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            InventoryVM inventory = new InventoryVM(_inventoryBL.GetInventoryById(id));
            ViewBag.Location = _locationBL.GetLocationById(inventory.LocationId);
            ViewBag.Product = _productBL.GetProductById(inventory.ProductId);
            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(InventoryVM inventoryVM)
        {
            try{
                if (ModelState.IsValid)
                {
                    _inventoryBL.UpdateInventory(new Inventory
                    {
                        Id = inventoryVM.Id,
                        Quantity = inventoryVM.Quantity,
                        LocationId = inventoryVM.LocationId,
                        ProductId = inventoryVM.ProductId
                    }

                    );
                    return RedirectToAction(nameof(ReplenishList), new { locationId = inventoryVM.LocationId} );
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreApp/WebUI/Controllers/LocationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;

namespace WebUI.Controllers
{
    
    public class LocationController : Controller
    {
        private ILocationBL _locationBL;
        private ICustomerBL _customerBL;
        public LocationController(ILocationBL locationBL, ICustomerBL customerBL)
        {
            _locationBL = locationBL;
            _customerBL = customerBL;
        }

        public ActionResult Index()
        {
            return View(_locationBL
            .GetAllLocations()
            .Select(location => new LocationVM(location))
            .ToList()
            );
        }
        
        public ActionResult SelectLocation(int customerId)
        {
            ViewBag.Customer = _customerBL.GetCustomerById(customerId);
            return View(_locationBL
            .GetAllLocations()
            .Select(location => new LocationVM(location))
            .ToList()
            );
        }
        
        public ActionResult Main(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            return View();
        }

        //GET
        public ActionResult Create()
        {
            return View();
        }
        
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LocationVM locationVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _locationBL.AddLocation(new Location
                    {
                        Name = locationVM.Name,
                        Address = locationVM.Address
                    });
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

StoreApp/WebUI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Linq;
using StoreBL;
using StoreModels;
using WebUI.Models;
using System.Collections.Generic;

namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductBL _productBL;
        private ILocationBL _locationBL;
        public ProductController(IProductBL productBL, ILocationBL locationBL)
        {
            _productBL = productBL;
            _locationBL = locationBL;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UnclaimedList(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);

            return View(_productBL
            .GetUnclaimedProducts(_locationBL.GetLocationById(locationId))
            .Select(prod => new ProductVM(prod))
            .ToList()
            );
        }

        //GET
        public ActionResult Create(int locationId)
        {
            ViewBag.Location = _locationBL.GetLocationById(locationId);
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductVM productVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _productBL.AddProduct(new Product
                    {
                        Name = productVM.Name,
                        Price = productVM.Price,
                        Description = productVM.Description
                    }
                    );
                    return RedirectToAction(nameof(UnclaimedList), new { locationId = productVM.LocationId });
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

    }
}

StoreApp/WebUI/Views/Product/Create.cshtml
@model WebUI.Models.ProductVM

@{
    ViewData["Title"] = "Create";
}

<h2>Branch: @ViewBag.Location.Name </h2>
<h4>Address: @ViewBag.Location.Address</h4>
<hr />
<br>
<h2>Create New Product</h2>
<h4>Enter Product Details</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="LocationId" value=@ViewBag.Location.Id/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Cancel", "UnclaimedList", "Product", new { locationId = ViewBag.Location.Id})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StoreApp/WebUI/Views/Product/HasInventory.cshtml
@model IEnumerable<WebUI.Models.ProductVM>
@{
    ViewData["Title"] = "HasInventory";
}

<h1>Branch: @ViewBag.Location.Name </h1>
<h4>Address: @ViewBag.Location.Address</h4>
<h3>Products have no inventory yet</h3>

<p>
    <a asp-action="Create">Create New Product</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Add Inventory", "Create", "Inventory", new { locationId = ViewBag.Location.Id, productId = item.Id }) |
            </td>
        </tr>
}
    </tbody>
</table>

StoreApp/WebUI/Views/Product/Index.cshtml
@model IEnumerable<WebUI.Models.ProductVM>
@{
    ViewData["Title"] = "Index";
}

<h1>New Products</h1>
<h1> Branch Name: @ViewBag.Location.Name </h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @* @Html.ActionLink("Edit", "Edit", new { id = item.Id }) | *@
                @Html.ActionLink("Add Inventory", "Index", "Inventory", new { id = item.Id }) |
                @* @Html.ActionLink("View Order History", "Index", "Review", new { id = item.Id }) | *@
            </td>
        </tr>
}
    </tbody>
</table>

StoreApp/WebUI/Views/Product/UnclaimedList.cshtml
@model IEnumerable<WebUI.Models.ProductVM>
@{
    ViewData["Title"] = "UnclaimedList";
}

<h2>Branch: @ViewBag.Location.Name </h2>
<h4>Address: @ViewBag.Location.Address</h4>
<hr />
<br>
<h3>List of Products</h3>

<p>
    &#128269;Can't find the Product. &#128073;
    @Html.ActionLink("Create new one", "Create", new {  locationId = ViewBag.Location.Id })
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Add Inventory", "Create", "Inventory", new { locationId = ViewBag.Location.Id, productId = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    @Html.ActionLink("Back to Main", "Main", "Location", new { locationId = ViewBag.Location.Id})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}